CREATE TABLE user_data(
    id UUID PRIMARY KEY UNIQUE NOT NULL
);

CREATE TABLE post(
    id INT PRIMARY KEY UNIQUE GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id UUID NOT NULL REFERENCES user_data(id),
    body VARCHAR(1000),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE post_like(
    id INT PRIMARY KEY UNIQUE GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id UUID NOT NULL REFERENCES user_data(id),
    post_id INT NOT NULL REFERENCES post(id)
);

CREATE TABLE post_photo(
    id INT PRIMARY KEY UNIQUE GENERATED ALWAYS AS IDENTITY NOT NULL,
    post_id INT NOT NULL REFERENCES post(id),
    photo_url VARCHAR(300) NOT NULL
);

CREATE TABLE comment(
    id INT PRIMARY KEY UNIQUE GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id UUID NOT NULL REFERENCES user_data(id),
    post_id INT NOT NULL REFERENCES post(id),
    body VARCHAR(400) NOT NULL,
    created_at TIMESTAMP,
    changed BOOLEAN
);

CREATE TABLE comment_like(
    id INT PRIMARY KEY UNIQUE GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id UUID NOT NULL REFERENCES user_data(id),
    comment_id INT NOT NULL REFERENCES comment(id)
);